### ISSUE TITLE
The type 'string' is not compatible with the type 'Text.ISourceText'

### ISSUE THREAD

**Issue by resolritter** [callmekohei/deopletefs#6]
Seems to be related to: https://github.com/fsprojects/FSharpLint/pull/342

`/programs/deopletefs/src/deopletefs.fsx(53,73): error FS0001: The type 'string' is not compatible with the type 'Text.ISourceText'`
`/programs/deopletefs/src/deopletefs.fsx(82,69): error FS0001: The type 'string' is not compatible with the type 'Text.ISourceText'`
`/programs/deopletefs/src/deopletefs.fsx(82,69): error FS0193: Type constraint mismatch. The type 'string'  is not compatible with type 'Text.ISourceText'`

## install log - bash build.bash
```
Paket version 5.215.0
Paket is already initialized in /programs/deopletefs
/programs/deopletefs/.paket/paket.targets
Downloading file from https://github.com/fsprojects/Paket/releases/download/5.215.0/paket.targets to /programs/deopletefs/.paket/paket.targets
/programs/deopletefs/.paket/paket.bootstrapper.exe
Downloading file from https://github.com/fsprojects/Paket/releases/download/5.215.0/paket.bootstrapper.exe to /programs/deopletefs/.paket/paket.bootstrapper.exe
Performance:
 - Runtime: 3 seconds
Paket version 5.215.0
Resolving packages for group Main:
 - NETStandard.Library 2.0.3
 - FSharp.Core 4.6.2
 - fsharp.compiler.service 30.0.0
 - newtonsoft.json 12.0.2
 - persimmon.script 4.0.0
 - System.ValueTuple 4.5.0
 - System.Net.Http 4.3.4
 - System.Reflection.Emit 4.3.0
 - System.Reflection.TypeExtensions 4.5.1
 - System.Security.Cryptography.Algorithms 4.3.1
 - Microsoft.Win32.Primitives 4.3.0
 - System.AppContext 4.3.0
 - System.Collections 4.3.0
 - System.Collections.Concurrent 4.3.0
 - System.Console 4.3.1
 - System.Diagnostics.Debug 4.3.0
 - System.Diagnostics.Tools 4.3.0
 - System.Diagnostics.Tracing 4.3.0
 - System.Globalization 4.3.0
 - System.Globalization.Calendars 4.3.0
 - System.IO 4.3.0
 - System.IO.Compression 4.3.0
 - System.IO.Compression.ZipFile 4.3.0
 - System.IO.FileSystem 4.3.0
 - System.IO.FileSystem.Primitives 4.3.0
 - System.Linq 4.3.0
 - System.Linq.Expressions 4.3.0
 - System.Net.Primitives 4.3.1
 - System.Net.Sockets 4.3.0
 - System.ObjectModel 4.3.0
 - System.Reflection 4.3.0
 - System.Reflection.Extensions 4.3.0
 - System.Reflection.Primitives 4.3.0
 - System.Resources.ResourceManager 4.3.0
 - System.Runtime 4.3.1
 - System.Runtime.Extensions 4.3.1
 - System.Runtime.Handles 4.3.0
 - System.Runtime.InteropServices 4.3.0
 - System.Runtime.InteropServices.RuntimeInformation 4.3.0
 - System.Runtime.Numerics 4.3.0
 - System.Security.Cryptography.Encoding 4.3.0
 - System.Security.Cryptography.Primitives 4.3.0
 - System.Security.Cryptography.X509Certificates 4.3.2
 - System.Text.Encoding 4.3.0
 - System.Text.Encoding.Extensions 4.3.0
 - System.Text.RegularExpressions 4.3.1
 - System.Threading 4.3.0
 - System.Threading.Tasks 4.3.0
 - System.Threading.Timer 4.3.0
 - System.Xml.ReaderWriter 4.3.1
 - System.Xml.XDocument 4.3.0
 - Microsoft.CSharp 4.5.0
 - System.ComponentModel.TypeConverter 4.3.0
 - System.Runtime.Serialization.Formatters 4.3.0
 - System.Runtime.Serialization.Primitives 4.3.0
 - System.Xml.XmlDocument 4.3.0
 - System.Diagnostics.Process 4.3.0
 - System.Net.Requests 4.3.0
 - System.Threading.ThreadPool 4.3.0
 - Persimmon 4.0.2
 - Persimmon.Runner 4.0.2
 - System.Linq.Queryable 4.3.0
 - System.Threading.Tasks.Parallel 4.3.0
 - System.Diagnostics.TraceSource 4.3.0
 - System.Runtime.Loader 4.3.0
 - System.Threading.Thread 4.3.0
 - System.Reflection.Metadata 1.6.0
 - System.Collections.Immutable 1.5.0
 - Microsoft.NETCore.Platforms 2.2.1
 - runtime.native.System.Security.Cryptography.OpenSsl 4.3.3
 - runtime.native.System.Security.Cryptography.Apple 4.3.1
 - System.Dynamic.Runtime 4.3.0
 - System.Collections.NonGeneric 4.3.0
 - System.Collections.Specialized 4.3.0
 - System.ComponentModel 4.3.0
 - System.ComponentModel.Primitives 4.3.0
 - Microsoft.Win32.Registry 4.5.0
 - runtime.native.System 4.3.1
 - runtime.native.System.IO.Compression 4.3.2
 - System.Buffers 4.5.0
 - System.Reflection.Emit.ILGeneration 4.3.0
 - System.Reflection.Emit.Lightweight 4.3.0
 - runtime.native.System.Net.Http 4.3.1
 - System.Diagnostics.DiagnosticSource 4.5.1
 - System.Globalization.Extensions 4.3.0
 - System.Security.Cryptography.OpenSsl 4.5.1
 - System.Net.WebHeaderCollection 4.3.0
 - System.Security.Cryptography.Cng 4.5.0
 - System.Security.Cryptography.Csp 4.3.0
 - System.Threading.Tasks.Extensions 4.5.2
 - Microsoft.NETCore.Targets 2.1.0
 - System.Runtime.CompilerServices.Unsafe 4.5.2
 - System.Memory 4.5.3
 - System.Security.AccessControl 4.5.0
 - System.Security.Principal.Windows 4.5.1
 - runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.3
 - runtime.debian.9-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.3
 - runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.3
 - runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.3
 - runtime.fedora.27-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.3
 - runtime.fedora.28-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.3
 - runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.3
 - runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.3
 - runtime.opensuse.42.3-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.3
 - runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.3
 - runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.3
 - runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.3
 - runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.3
 - runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.3
 - runtime.ubuntu.18.04-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.3
 - runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple 4.3.1
 - System.Numerics.Vectors 4.5.0
Locked version resolution written to /programs/deopletefs/paket.lock
Installing into projects:
 - Creating model and downloading packages.
Downloading FSharp.Compiler.Service 30.0.0
Downloading System.Security.Cryptography.OpenSsl 4.5.1
Downloading System.Console 4.3.1
Downloading System.Memory 4.5.3
Downloading System.Runtime.Serialization.Formatters 4.3.0
Download of System.Security.Cryptography.OpenSsl 4.5.1 done in 3 seconds. (496 kbit/s, 0 MB)
Downloading System.Text.RegularExpressions 4.3.1
Download of System.Console 4.3.1 done in 6 seconds. (127 kbit/s, 0 MB)
Still downloading from https://www.nuget.org/api/v2/package/FSharp.Compiler.Service/30.0.0 to /home/joaopaulo/.nuget/packages/fsharp.compiler.service/30.0.0d5qdhxgc.3w4.paket_tmp (6729 kbit/s, Unknown %)
Download of System.Runtime.Serialization.Formatters 4.3.0 done in 6 seconds. (93 kbit/s, 0 MB)
Download of System.Memory 4.5.3 done in 7 seconds. (167 kbit/s, 0 MB)
Downloading System.Net.Primitives 4.3.1
Download of FSharp.Compiler.Service 30.0.0 done in 11 seconds. (6072 kbit/s, 8 MB)
Download of System.Text.RegularExpressions 4.3.1 done in 6 seconds. (682 kbit/s, 0 MB)
Downloading Microsoft.CSharp 4.5.0
Downloading System.Threading.Tasks.Parallel 4.3.0
Download of System.Net.Primitives 4.3.1 done in 2 seconds. (2222 kbit/s, 0 MB)
Downloading System.Net.Requests 4.3.0
Download of Microsoft.CSharp 4.5.0 done in 2 seconds. (1811 kbit/s, 0 MB)
Downloading Microsoft.NETCore.Platforms 2.2.1
Download of System.Threading.Tasks.Parallel 4.3.0 done in 3 seconds. (448 kbit/s, 0 MB)
Downloading System.ValueTuple 4.5.0
Download of System.Net.Requests 4.3.0 done in 2 seconds. (1259 kbit/s, 0 MB)
Download of Microsoft.NETCore.Platforms 2.2.1 done in 2 seconds. (124 kbit/s, 0 MB)
Downloading System.Net.WebHeaderCollection 4.3.0
Downloading Newtonsoft.Json 12.0.2
Download of System.ValueTuple 4.5.0 done in 2 seconds. (710 kbit/s, 0 MB)
Download of System.Net.WebHeaderCollection 4.3.0 done in 1 second. (349 kbit/s, 0 MB)
Downloading System.Xml.ReaderWriter 4.3.1
Download of Newtonsoft.Json 12.0.2 done in 5 seconds. (3411 kbit/s, 2 MB)
Download of System.Xml.ReaderWriter 4.3.1 done in 4 seconds. (2405 kbit/s, 1 MB)
Downloading Persimmon 4.0.2
Download of Persimmon 4.0.2 done in 2 seconds. (599 kbit/s, 0 MB)
Downloading Persimmon.Runner 4.0.2
Download of Persimmon.Runner 4.0.2 done in 2 seconds. (187 kbit/s, 0 MB)
Downloading Persimmon.Script 4.0.0
Download of Persimmon.Script 4.0.0 done in 2 seconds. (78 kbit/s, 0 MB)
 - Installing for projects
Performance:
 - Resolver: 1 minute, 8 seconds (1 runs)
    - Runtime: 8 seconds
    - Blocked (retrieving package details): 52 seconds (48 times)
    - Blocked (retrieving package versions): 8 seconds (6 times)
    - Not Blocked (retrieving package details): 64 times
    - Not Blocked (retrieving package versions): 106 times
 - Disk IO: 8 seconds
 - Average Download Time: 1 second
 - Number of downloads: 18
 - Average Request Time: 203 milliseconds
 - Number of Requests: 347
 - Runtime: 1 minute, 45 seconds
```
